var str1 = "Himanshu";
var str2 = "John";
var str3 = "John Doe";
var userName = "Himanshu Sinha";
var age = 35;
console.log("userName is ".concat(userName, " and age is ").concat(age));
var num = 100;
var str = num.toString();
console.log(typeof str);
var strs = "" + str;
console.log(typeof strs);
var bool = true;
// var data2: string = "" + bool;
var data2 = bool.toString();
console.log(data2);
var data3 = true;
console.log(data3);
var itemm = true;
var other;
other = itemm;
console.log(other);
